/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/black-dragon-with-idle-animation-fb0053a2e59b43868e934c239bf4eb36
Title: Black Dragon with Idle Animation
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";
import DragonModel from "../assets/black_dragon_with_idle_animation.glb";

const Dragon = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(DragonModel);
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["Scene"].play();
  }, []);
  return (
    <a.group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.002}
        >
          <group
            name="aeeb858164ee4e0884da4001c74b8628fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Hemi"
                  position={[4018.555, 4666.064, 3759.082]}
                  rotation={[-2.595, 0.261, 0.387]}
                  scale={100}
                >
                  <group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_6" />
                  </group>
                </group>
                <group
                  name="Plane"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                ></group>
                <group
                  name="Dragon_Idle"
                  rotation={[Math.PI, 0, 0]}
                  scale={100}
                >
                  <group name="Object_10">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_244"
                      geometry={nodes.Object_244.geometry}
                      material={materials.EYES}
                      skeleton={nodes.Object_244.skeleton}
                    />
                    <skinnedMesh
                      name="Object_245"
                      geometry={nodes.Object_245.geometry}
                      material={materials.Game_dragon}
                      skeleton={nodes.Object_245.skeleton}
                    />
                    <skinnedMesh
                      name="Object_246"
                      geometry={nodes.Object_246.geometry}
                      material={materials["Game_dragon.001"]}
                      skeleton={nodes.Object_246.skeleton}
                    />
                    <group
                      name="Object_243"
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                  </group>
                </group>
                <group
                  name="Dragon"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  );
};

export default Dragon;
